2024-01-31 15:16:26.966 [info] (Client) Pylance async client (2023.12.1) started with python extension (2023.22.1)
2024-01-31 15:16:27.742 [info] [Info  - 3:16:27 PM] (20514) Pylance language server 2023.12.1 (pyright a78e2b10) starting
2024-01-31 15:16:27.742 [info] [Info  - 3:16:27 PM] (20514) Server root directory: /home/holden/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist
2024-01-31 15:16:27.743 [info] [Info  - 3:16:27 PM] (20514) Starting service instance "Haueauuark"
2024-01-31 15:16:27.816 [info] [Info  - 3:16:27 PM] (20514) Setting pythonPath for service "Haueauuark": "/bin/python"
2024-01-31 15:16:27.816 [info] [Info  - 3:16:27 PM] (20514) Setting environmentName for service "Haueauuark": "3.11.5 (global)"
2024-01-31 15:16:27.861 [info] [Info  - 3:16:27 PM] (20514) Assuming Python version 3.11
2024-01-31 15:16:27.964 [info] [Info  - 3:16:27 PM] (20514) Found 1 source file
2024-01-31 15:19:03.971 [info] [Error - 3:19:03 PM] Server process exited with code 0.
